In [1]:
import os.path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

np.set_printoptions(suppress=True)
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
file_folder = '/home/anna/annaCode/UiO/MEK4350/notebooks/Data_undervisning200923'
date_format = '%m/%d/%Y %H:%M:%S.%f'

mean_water_level = np.empty(16)
still_level_t0 = np.empty(16)
j = 0
df_list = []
for i in range(1,5):
    file_path =  os.path.join(file_folder, f"proberun{i}_tett.csv")
    df = pd.read_csv(file_path, names = ['date_string', 'probe_1_raw', 'probe_2_raw', 'probe_3_raw', 'probe_4_raw', 'sensors'])
    # convert data from string to datatime format
    df['date_time'] = pd.to_datetime(df['date_string'], format=date_format)
    # calculate elapsed time [in seconds] since  begining of the experiment
    df['elapsed_secs'] =  (df['date_time'] - df.at[0, 'date_time']).dt.total_seconds()
    #calculate amplitudes; raw columns oryginaly contain vertical distance from utrasound probe, covert it distance from water level 
    for k in range(1,5):
        df[f'probe_{k}'] = df[f'probe_{k}_raw'].mean() - df[f'probe_{k}_raw']
        mean_water_level[j] =  df[f'probe_{k}_raw'].mean()
        still_level_t0[j] = df.head(120)[f'probe_{k}_raw'].mean()
        j += 1
  
    df_list.append(df)
    
df = df_list[0]
df.head(2)

date_string  probe_1_raw  probe_2_raw  probe_3_raw  \
0  09/20/2023 08:42:24.832      0.10401      0.10358      0.10444   
1  09/20/2023 08:42:24.836      0.10410      0.10358      0.10444   

   probe_4_raw  sensors               date_time  elapsed_secs   probe_1  \
0      0.10367   343.87 2023-09-20 08:42:24.832         0.000 -0.000255   
1      0.10367   343.87 2023-09-20 08:42:24.836         0.004 -0.000345   

    probe_2   probe_3   probe_4  
0 -0.000142 -0.000671  0.000152  
1 -0.000142 -0.000671  0.000152

In [3]:
#max "height" of wave in first experiment (not real height, more difference between heighest crest and lowest trough)
ex1_max_height = df[f'probe_1_raw'].max() - df[f'probe_1_raw'].min()
ex1_max_height

0.03432

In [4]:
#probe 1 - mean water level vs still water level before experiment started
probe1_indices = np.arange(0,16,4)
mean_water_level[probe1_indices], still_level_t0[probe1_indices], mean_water_level[probe1_indices].std(), still_level_t0[probe1_indices].std()

(array([0.10375521, 0.10387313, 0.10388745, 0.10447902]),
 array([0.10446892, 0.10451408, 0.10455058, 0.1045365 ]),
 0.00028202067269695355,
 3.093347336310774e-05)

In [5]:
#probe 2 - mean water level vs still water level before experiment started
mean_water_level[probe1_indices + 1],  still_level_t0[probe1_indices +1], mean_water_level[probe1_indices + 1].std(), still_level_t0[probe1_indices +1].std()

(array([0.10343754, 0.10354402, 0.10353899, 0.10415094]),
 array([0.10446325, 0.10457375, 0.104593  , 0.10609875]),
 0.0002821141408897708,
 0.000675332519370075)

In [6]:
#probe 3 - mean water level vs still water level before experiment started
mean_water_level[probe1_indices + 2], still_level_t0[probe1_indices +2], mean_water_level[probe1_indices + 2].std(), still_level_t0[probe1_indices +2].std()

(array([0.1037693 , 0.10385982, 0.10387449, 0.10435703]),
 array([0.10433575, 0.10458475, 0.10458383, 0.106482  ]),
 0.0002298079500900661,
 0.0008635873761524659)

In [7]:
#probe 4 - mean water level vs still water level before experiment started
mean_water_level[probe1_indices + 3], still_level_t0[probe1_indices +3], mean_water_level[probe1_indices + 3].std(), still_level_t0[probe1_indices +3].std()

(array([0.10382169, 0.10405153, 0.10389703, 0.10404296]),
 array([0.103859  , 0.10407933, 0.10405933, 0.10411458]),
 9.769267762096016e-05,
 9.959235271212465e-05)

In [8]:
diff = abs(mean_water_level - still_level_t0)

diff.max(), diff.min()

(0.002124965416073543, 2.7806276390263118e-05)

In [9]:
max_diff = diff.max()

In [10]:
percent_error = max_diff/ex1_max_height * 100
percent_error

6.191624172708458

In [11]:
mean_water_level.std(), still_level_t0.std()

(0.00027024772080347104, 0.0006732185271534491)